[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions."lock-period"]
  schedule = "0 5 * * *"

[functions."reminder-cron"]
  schedule = "0 14 * * *"
